PFC/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    # -------------------------------------------------------------------------------
    # URLs para los usuarios
    # -------------------------------------------------------------------------------
    url(r'^usuarios/lista/$', views.user_list, name='user_list'),
    url(r'^usuarios/nuevo/$', views.new_user, name='new_user'),
    url(r'^usuarios/editar/(?P<pk>[0-9]+)/$', views.edit_user, name='edit_user'),
    url(r'^usuarios/borrar/(?P<pk>[0-9]+)/$', views.delete_user, name='delete_user'),
    url(r'^usuarios/info/(?P<pk>[0-9]+)/$', views.user_info, name='user_info'),
    # -------------------------------------------------------------------------------
    # URLs para los lugares
    # -------------------------------------------------------------------------------
    url(r'^lugares/lista/(?P<tp>[a-z]+)/$', views.place_list, name='place_list'),
    url(r'^lugares/nuevo/(?P<tp>[a-z]+)/$', views.new_place, name='new_place'),
    url(r'^lugares/editar/(?P<pk>[0-9]+)/$', views.edit_place, name='edit_place'),
    url(r'^lugares/borrar/(?P<pk>[0-9]+)/(?P<list>[a-z]+)/$', views.delete_place, name='delete_place'),
    url(r'^lugares/info/(?P<pk>[0-9]+)/$', views.place_info, name='place_info'),
    url(r'^X/$', TemplateView.as_view(template_name='nolugares.html'), name='nolugares'),
    # -------------------------------------------------------------------------------
    # URLs para administración
    # -------------------------------------------------------------------------------
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^stop/$', TemplateView.as_view(template_name='denied.html'), name='denied'),
    url(r'^roladmin/(?P<pk>[0-9]+)/$', views.addtoadmin, name='addtoadmin'),
    url(r'^rolusers/(?P<pk>[0-9]+)/$', views.addtousers, name='addtousers'),
    # -------------------------------------------------------------------------------
    # URLs de funcionamiento de la aplicación
    # -------------------------------------------------------------------------------
    url(r'^$', views.home, name='home'),
    url(r'^favoritos/$', views.favoritos, name='favoritos'),
    url(r'^votos/$', views.votos, name='votos'),
    url(r'^ayuda/$', TemplateView.as_view(template_name='ayuda.html'), name='ayuda'),
    url(r'^galeria/(?P<pk>[0-9]+)/$', views.galery, name='galery'),
    url(r'^galeria/add/(?P<pk>[0-9]+)/$', views.add_photo, name='add_photo'),
    url(r'^galeria/del/(?P<pk>[0-9]+)/$', views.del_photo, name='del_photo'),
    url(r'^recomendaciones/$', views.recomend, name='recomend'),
    url(r'^recomendaciones/resultados/$', views.recomendaciones, name='recomendaciones'),
    # -------------------------------------------------------------------------------
    # URLs para la web API
    # -------------------------------------------------------------------------------
    url(r'^getSites/$', views.getSites, name='getSites'),
    url(r'^getPlaceDetails/$', views.getPlaceDetails, name='getPlaceDetails'),
    url(r'^getRecommendations/$', views.getRecommendations, name='getRecommendations'),
    url(r'^setFavorite/$', views.setFavorite, name='setFavorite'),
    url(r'^setFeedback/$', views.setFeedback, name='setFeedback'),
    url(r'^createUser/$', views.createUser, name='createUser'),
    url(r'^deleteUser/$', views.deleteUser, name='deleteUser'),


    url(r'^mapa/$', TemplateView.as_view(template_name='mapa.html'), name='mapa'),
    url(r'^test/$', TemplateView.as_view(template_name='test.html'), name='test'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('PFC.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

PFC/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import URLField, CASCADE
from multiselectfield import MultiSelectField
from easy_thumbnails.signals import saved_file
from easy_thumbnails.signal_handlers import generate_aliases_global

saved_file.connect(generate_aliases_global)


# -------------------------------------------------------------------------------
# MODELO perfil de usuario
# -------------------------------------------------------------------------------
class Profile(models.Model):
    Administradores = 'administradores'
    Usuarios = 'usuarios'
    TIPOS = (
        (Administradores, 'Administrador'),
        (Usuarios, 'Usuario'),
    )
    CAT0 = 0
    CAT1 = 1
    CAT2 = 2
    CAT3 = 3
    CAT4 = 4
    CAT5 = 5
    CAT6 = 6
    CAT7 = 7
    CAT8 = 8
    CATS = (
        (CAT0, 'Arte y Diseño'),
        (CAT1, 'Arquitectura'),
        (CAT2, 'Historia'),
        (CAT3, 'Ciencia y Tecnología'),
        (CAT4, 'Naturaleza'),
        (CAT5, 'Aventura'),
        (CAT6, 'Literatura'),
        (CAT7, 'Música'),
        (CAT8, 'Vida urbana'),
    )
    CLARO = '1'
    OSCURO = '2'
    SIMPLE = '3'
    CSS = (
        (CLARO, 'CLARO'),
        (OSCURO, 'OSCURO'),
        (SIMPLE, 'SIMPLE'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    tipo = models.CharField(max_length=20, choices=TIPOS, verbose_name='Rol')
    nombre = models.CharField(max_length=25, verbose_name='Nombre', null=True, blank=True)
    apellidos = models.CharField(max_length=35, verbose_name='Apellidos', null=True, blank=True)
    correo = models.EmailField(verbose_name='Correo electrónico', null=True, blank=True)
    cat_preferidas = MultiSelectField(choices=CATS, max_choices=9, verbose_name='Categorías', null=True, blank=True)
    css = models.CharField(max_length=1, choices=CSS, default=CLARO, verbose_name='Estilo de la web')

    def __str__(self):
        return self.user.username

# -------------------------------------------------------------------------------
# MODELO lugar
# -------------------------------------------------------------------------------
class Place(models.Model):
    CAT0 = 0
    CAT1 = 1
    CAT2 = 2
    CAT3 = 3
    CAT4 = 4
    CAT5 = 5
    CAT6 = 6
    CAT7 = 7
    CAT8 = 8
    CATS = (
        (CAT0, 'Arte y Diseño'),
        (CAT1, 'Arquitectura'),
        (CAT2, 'Historia'),
        (CAT3, 'Ciencia y Tecnología'),
        (CAT4, 'Naturaleza'),
        (CAT5, 'Aventura'),
        (CAT6, 'Literatura'),
        (CAT7, 'Música'),
        (CAT8, 'Vida urbana'),
    )
    tipos = (
        ('site', 'Sitio'),
        ('poi', 'Punto de Interés'),
    )
    ref = models.ForeignKey('Place', on_delete=CASCADE, blank=True, null=True)
    tipo = models.CharField(choices=tipos, max_length=4)
    name = models.CharField(max_length=50, verbose_name='Nombre')
    description = models.TextField(verbose_name='Descripción')
    image = models.ImageField(verbose_name='Imagen de portada')
    latitude = models.DecimalField(max_digits=9, decimal_places=7, verbose_name='Latitud', validators=[MaxValueValidator(90.0), MinValueValidator(-90.0)])
    longitude = models.DecimalField(max_digits=10, decimal_places=7, verbose_name='Longitud', validators=[MaxValueValidator(180.0), MinValueValidator(-180.0)])
    categorias = MultiSelectField(choices=CATS, max_choices=9, verbose_name='Categorías')
    url = URLField(verbose_name='URL')
    rating = models.IntegerField(verbose_name='Puntuación media', validators=[MaxValueValidator(100), MinValueValidator(0)])
    votes = models.IntegerField(verbose_name='Número de votos')
    likes = models.IntegerField(verbose_name='Número de veces favorito', null=True, blank=True)
    author = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.name

    def nota(self):
        resultado = self.rating / 10
        return resultado

    class Meta:
        ordering = ['name']

# -------------------------------------------------------------------------------
# MODELO fotografías asociadas a los lugares
# -------------------------------------------------------------------------------
class Photo(models.Model):
    place = models.ForeignKey(Place, verbose_name='Lugar de referencia')
    image = models.ImageField(verbose_name='Imagen')
    # thumbnail = models.CharField(max_length=200)

    def __str__(self):
        return self.place_id


# -------------------------------------------------------------------------------
# MODELO para establecer lugares favoritos
# -------------------------------------------------------------------------------
class Favoritos(models.Model):
    usuario = models.ForeignKey(User, null=True, blank=True)
    lugar = models.ForeignKey(Place, null=True, blank=True)

# -------------------------------------------------------------------------------
# MODELO para votar lugares
# -------------------------------------------------------------------------------
class Votos(models.Model):
    usuario = models.ForeignKey(User, null=True, blank=True)
    lugar = models.ForeignKey(Place, null=True, blank=True)
    valor = models.IntegerField(verbose_name='Puntuación media inicial', validators=[MaxValueValidator(100), MinValueValidator(0)])

PFC/forms.py
from django import forms
from django.forms import TextInput
from .models import Profile, Place, Photo, Favoritos, Votos


# -------------------------------------------------------------------------------
# FORMULARIO perfil de usuario
# -------------------------------------------------------------------------------
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('nombre', 'apellidos', 'correo', 'cat_preferidas', 'css')
        widgets = {
            'nombre': TextInput(attrs={'placeholder': 'Introduce el nombre', 'size': '35'}),
            'apellidos': TextInput(attrs={'placeholder': 'Introduce los apellidos', 'size': '35'}),
            'correo': TextInput(attrs={'placeholder': 'Introduce el correo electrónico', 'size': '35'})
        }
        labels = {
            'nombre': 'Nombre',
            'apellidos': 'Apellidos',
            'correo': 'email',
            'cat_preferidas': 'Preferencias',
            'css': 'Elegir estilo de la web'
        }

# -------------------------------------------------------------------------------
# FORMULARIO lugar
# -------------------------------------------------------------------------------
class PlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = ('ref', 'tipo', 'name', 'description', 'image', 'categorias', 'latitude', 'longitude', 'url', 'rating')

# -------------------------------------------------------------------------------
# FORMULARIO marcar lugares favoritos
# -------------------------------------------------------------------------------
class FavoritosForm(forms.ModelForm):
    class Meta:
        model = Favoritos
        fields = ('usuario', 'lugar')

# -------------------------------------------------------------------------------
# FORMULARIO para votar lugares
# -------------------------------------------------------------------------------
class VotosForm(forms.ModelForm):
    class Meta:
        model = Votos
        fields = ('usuario', 'lugar', 'valor')

# -------------------------------------------------------------------------------
# FORMULARIO para las fotografías asociadas a los lugares
# -------------------------------------------------------------------------------
class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('place', 'image')


# -------------------------------------------------------------------------------
# FORMULARIO para averiguar las coordenadas de una dirección
# -------------------------------------------------------------------------------
class AddressForm(forms.Form):
    address = forms.CharField(max_length=100, label="Localidad", required=True)

# -------------------------------------------------------------------------------
# FORMULARIO para establecer la posición del dispositivo vía IP
# -------------------------------------------------------------------------------
class LatLonForm(forms.Form):
    lat = forms.DecimalField(label='latitud', required=True)
    lon = forms.DecimalField(label='longitud', required=True)

PFC/templates/ayuda.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="es">
<head>
    {% include 'f_head.html' %}
</head>

<body id="bodi">
{% if request.user.profile.css == "3" %}
{% include 'navbarsimple4.html' %}
{% include 'carrusel.html' %}
<div class="container text-left"><br>
{% else %}
{% include 'navbar4.html' %}
{% include 'carrusel.html' %}
<div class="container text-left"><br>
{% endif %}

    <div class="row col-xs-12 col-sm-12 col-md-10 col-lg-9">
        <div class="panel-group" id="desplegable">

            {% if perms.PFC.add_place %}
            <h2>Preguntas frecuentes de un editor de contenido</h2><br>
            <div class="panel">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <a data-toggle="collapse" data-parent="#desplegable" href="#E01">¿Cómo creo un nuevo lugar?</a>
                    </h2>
                </div>
                <div id="E01" class="panel-collapse collapse">
                    <div class="panel-body">Puedes hacerlo fácilmente desde tu perfil mediante los enlaces dedicados para la creación de sitios y de puntos de interés</div>
                </div>
            </div>
            <div class="panel">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <a data-toggle="collapse" data-parent="#desplegable" href="#E02">¿Cómo añado fotos a un lugar?</a>
                    </h2>
                </div>
                <div id="E02" class="panel-collapse collapse">
                    <div class="panel-body">Puedes llevar a cabo esta situación desde cualquier sitio en que veas este icono <span class="glyphicon glyphicon-picture"></span>+  Lo podrás encontrar en tu perfil, en la sección "Mis lugares creados", así como en cualquier lista de lugares y en la propia ficha del lugar que quieras completar con fotografías extra.</div>
                </div>
            </div>
            <br>
            {% endif %}

    <h2>Preguntas frecuentes</h2><br>


            <div class="panel">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <a data-toggle="collapse" data-parent="#desplegable" href="#D04">¿Qué podré ver si me registro?</a>
                    </h2>
                </div>
                <div id="D04" class="panel-collapse collapse">
                    <div class="panel-body">Como usuario registrado podrás acceder a todo el contenido de la aplicación, lo que incluye una serie de lugares con información muy interesante. Por ejemplo podrás ver qué valoración tiene ese lugar según los votos de otros usuarios, dónde está en un mapa, imáganes de lo que te encontrarías si decides visitarlo, etc.<br><br>Además podrás acceder a un sistema de recomendaciones donde a partir de tus preferencias buscaremos los lugares más apropiados para ti</div>
                </div>
            </div>
            <div class="panel">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <a data-toggle="collapse" data-parent="#desplegable" href="#D07">¿Qué es un sitio? ¿Y un punto de interés?</a>
                    </h2>
                </div>
                <div id="D07" class="panel-collapse collapse">
                    <div class="panel-body">Ambos son lugares. La diferencia radica en su categoría. Los Sitios son lugares que por su magnitud o interés destacan de forma muy notable. Los Puntos de Interés suelen ser más pequeños o tener una importancia más relativa. Pero a cualquier otro efecto, ambos son idénticos.</div>
                </div>
            </div>
            <div class="panel">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <a data-toggle="collapse" data-parent="#desplegable" href="#D05">¿Cómo está organizada la aplicación?</a>
                    </h2>
                </div>
                <div id="D05" class="panel-collapse collapse">
                    <div class="panel-body">En la parte superior podrás acceder a todo el contenido de la aplicación mediante un intuitivo menú.<br><br>En la ficha "Mi Perfil" encontrarás un área personal con tus datos y preferencias.<br>En la pestaña "Lugares" encontrarás los diferentes sitios y puntos de interés almacenados en la web. Desde aquí podrás acceder a sus fichas con toda la información que tenemos de ellos<br>Si pinchas en "Recomendador" accederás al sistema de recomendaciones personales. <br>Y la pestaña "Ayuda" ya la conoces. Estamos en ella para resolver tus dudas.</div>
                </div>
            </div>
            <div class="panel">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <a data-toggle="collapse" data-parent="#desplegable" href="#D01">¿Cómo puedo registrarme?</a>
                    </h2>
                </div>
                <div id="D01" class="panel-collapse collapse">
                    <div class="panel-body">Puedes registrarte pinchando en <a class="ayuda_a" href="{% url 'new_user' %}">este enlace</a> o en el que hay para ello en la página de inicio.
                    También puedes hacerlo desde el enlace que verás en la página de login cuando intentes acceder a contenido sólo para usuarios registrados.</div>
                </div>
            </div>
            <div class="panel">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <a data-toggle="collapse" data-parent="#desplegable" href="#D02">¿Cómo puedo ver la información de los lugares?</a>
                    </h2>
                </div>
                <div id="D02" class="panel-collapse collapse">
                    <div class="panel-body">Tienes que estar registrado para verla. Si no lo estás, regístrate <a class="ayuda_a" href="{% url 'new_user' %}">aquí</a>. Luego, pincha en la pestaña de Lugares
                    y a continuación en Todos los lugares, Sitios, o Puntos de Interés. Verás los resultados en pantalla. Pincha en cualquier lugar que
                    quieras para ver su ficha con la información.</div>
                </div>
            </div>
            <div class="panel">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <a data-toggle="collapse" data-parent="#desplegable" href="#D03">¿Qué es "Mi Perfil"?</a>
                    </h2>
                </div>
                <div id="D03" class="panel-collapse collapse">
                    <div class="panel-body">"Mi Perfil" es un espacio personal donde podrás encontrar tus datos personales, así como editarlos. También podrás borrar tu cuenta de usuario si decides que ya no quieres estar con nosotros, aunque esperamos que eso no suceda :)</div>
                </div>
            </div>
            <div class="panel">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <a data-toggle="collapse" data-parent="#desplegable" href="#D06">¿Pregunta?</a>
                    </h2>
                </div>
                <div id="D06" class="panel-collapse collapse">
                    <div class="panel-body">Vacío</div>
                </div>
            </div>




            </div>
        </div>



    </div><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
</div>
{% include 'footer2.html' %}
</body>
</html>

PFC/templates/denied.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="es">
<head>
  {% include 'f_head.html' %}
  <style>


  </style>
</head>
<body id="bodi">
{% include 'navbar0.html' %}
{% include 'carrusel.html' %}

<div class="container text-left">
  <h2>Bienvenido a mi proyecto</h2><br>
  {% if user.is_authenticated %}
  <p>Lamentablemente no tienes los permisos necesarios para completar esta acción...</p>
  {% else %}
  <form method="POST">
    {% csrf_token %}
    <label for="username">Usuario:</label>
    <input type="text" name="username">
    <label for="password">Contraseña:</label>
    <input type="password" name="password">
    <button class=".btn-success" type="submit" name="login">Login</button>
  </form>
  {% endif %}
</div><br>
{% include 'footer.html' %}

</body>
</html>

PFC/templates/galeria.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="es">
<head>
    {% include 'f_head.html' %}
    <link rel="stylesheet" href="{% static 'css/lightbox.css' %}">
    <script src="{% static 'js/lightbox.js' %}"></script>
</head>
<body id="bodi">

{% include 'navbar0.html' %}
{% include 'carrusel.html' %}

<div class="container text-left"><br>
    <h2>Galería de imágenes</h2><br>
    {% if not item_list %}
    <p>Lo sentimos, no hay imágenes para mostrar de momento</p>
    {% else %}
    {% for item in item_list %}
    <a class="lightbox" title="" href="{{ item.image.url }}"><img class="imagaleria img-thumbnail" src="{{ item.image.url }}" alt="imagen sin nombre" /></a>
    {% endfor %}
    {% endif %}
</div><br>
{% include 'footer.html' %}
<script src="{% static 'js/lightboxcustom.js' %}"></script>
</body>
</html>

PFC/templates/logout.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>

</head>
<body>
<form method="post">
    {% csrf_token %}
    <label for="username">Usuario:</label>
    {{ form.username }}
    <label for="password">Contraseña:</label>
    {{ form.password }}

    <button type="submit" name="login">Login</button>
</form>
</body>
</html>

PFC/templates/new_user.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="es">
<head>
    {% include 'f_head.html' %}
    <style>
        span.form-control > input{
            border: none;
            border-right: 1px solid #EEEEEE;
            background-color: transparent;
        }
    </style>
</head>
<body id="bodi">
{% include 'navbar1.html' %}
{% include 'carrusel.html' %}

<div class="container text-left"><br>
    <h2>Nuevo usuario</h2><br>

    <form method="post" enctype="multipart/form-data" class="form-horizontal">
        {% csrf_token %}
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="form-group">
                    <h2>PASO 1: Datos de registro</h2>
                    <p>Estos datos son necesarios para registrarte en el sistema. Los campos marcados con un asterisco * son obligatorios</p>
                    </div>

                <div class="form-group">
                    <label class="control-label col-xs-12 col-sm-4 col-md-4 col-lg-4" for="id_username">* Nombre de usuario en el sistema: </label>
                    <div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">
                        <input type="text" class="form-control" placeholder="Sólo caracteres alfanuméricos y @ . + - _ sin espacios" name="username">
                        {% if form.username.errors %}<span class="spanerror">  * necesario. Sólo caracteres alfanuméricos y @ . + - _ sin espacios</span>{% endif %}
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-xs-12 col-sm-4 col-md-4 col-lg-4" for="id_password1">* Contraseña: </label>
                    <div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">
                        <input type="password" class="form-control" placeholder="Introduce tu password" name="password1">
                        {% if form.password1.errors %}<span class="spanerror">  * necesario</span>{% endif %}
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-xs-12 col-sm-4 col-md-4 col-lg-4" for="id_password2">* Repite la contraseña: </label>
                    <div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">
                        <input type="password" class="form-control" placeholder="Introduce tu password de nuevo" name="password2">
                        {% if form.password2.errors %}<span class="spanerror">  * necesario. Debe coincidir con el campo contraseña</span>{% endif %}
                    </div>
                </div>

                <br><hr style="border-top:2px solid #000000;"><br>
                <div class="form-group">

                    <h2>PASO 2 (OPCIONAL) - Datos personales</h2>
                    <p>Si nos facilitas estos datos, aparecerán en tu perfil, y podremos contactar contigo en caso necesario, así como ofrecerte recomendaciones personalizadas si nos dices tus preferencias. En cualquier caso estos datos no se divulgarán a terceros y podrás borrarlos en cualquier momento editando tu perfil.</p>
                    </div>
                </div>


                {% for field in profile_form %}
                {% if field.name == "tipo" %}
                <div class="form-group">
                    <label class="control-label col-xs-12 col-sm-4 col-md-4 col-lg-4" for="{{field.id_for_label}}">{{field.label}}: </label>
                    <div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">
                        <span class="form-control">{{field}}</span>
                        {% if field.errors %}<span class="spanerror">  * verifica que los datos son correctos</span>{% endif %}
                    </div>
                </div>
                {% else %}
                <div class="form-group">
                    <label class="control-label col-xs-12 col-sm-4 col-md-4 col-lg-4" for="{{field.id_for_label}}">{{field.label}}: </label>
                    <div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">
                        {% if field.name == "cat_preferidas" %}
                        <br><br>{{ field }}<br>
                        {% elif field.name == "css"%}
                        <br>
                        <p>Selecciona uno. Puedes previsualizar los estilos pinchando en los siguientes botones. El estilo "SIMPLE" está especialmente diseñado para personas menos jóvenes <img style="width: 1.5em; vertical-align: text-top;" src="{% static 'img/emo_feliz.png' %}" alt="emoticono feliz"/></p>
                        {{ field }}<span>&nbsp;&nbsp;&nbsp;</span>
                        <span data-toggle="modal" data-target="#temaclaro"><button type="button" class="btn btn-default" data-toggle="muestraclaro">CLARO</button></span>
                        <span data-toggle="modal" data-target="#temaoscuro"><button type="button" class="btn btn-default" data-toggle="muestraoscuro">OSCURO</button></span>
                        <span data-toggle="modal" data-target="#temasimple"><button type="button" class="btn btn-default" data-toggle="muestrasimple">SIMPLE</button></span><br><br>
                        {% else %}
                        <input type="text" class="form-control" name="{{field.name}}" placeholder="(campo opcional)">{% if form.field.errors %}<span class="spanerror">  * error en los datos</span>{% endif %}
                        {% if field.errors %}<span class="spanerror">  * Error. Verifica que todo está correcto</span>{% endif %}
                        {% endif %}
                    </div>
                </div>




                {% endif %}
                {% endfor %}

                <div id="divtest2"></div>
                <div class="form-group">
                    <label class="control-label col-xs-6 col-sm-5 col-md-4 col-lg-4" for=""> </label>
                    <div class="col-xs-3 col-sm-4 col-md-4 col-lg-4 text-center">
                        <button type="submit" class="btn-danger btn-lg">CREAR</button><br><br>
                    </div>
                </div>

            </div>
        </div>
    </form>


</div>
<br><br>
{% include 'footer.html' %}
{% include 'modaltemaclaro.html' %}
{% include 'modaltemaoscuro.html' %}
{% include 'modaltemasimple.html' %}
<script>
$(document).ready(function(){
    $('[data-toggle="muestraclaro"]').tooltip({title: "<img src=\"{% static 'img/cssclaro.jpg' %}\" width=\"100%\" style=\"border: 3px solid #000000;\">", html: true, placement: "auto"});
    $('[data-toggle="muestraoscuro"]').tooltip({title: "<img src=\"{% static 'img/cssoscuro.jpg' %}\" width=\"100%\" style=\"border: 3px solid #000000;\">", html: true, placement: "auto"});
    $('[data-toggle="muestrasimple"]').tooltip({title: "<img src=\"{% static 'img/csssimple.jpg' %}\" width=\"100%\" style=\"border: 3px solid #000000;\">", html: true, placement: "auto"});
});
</script>
<script>
  if (typeof navigator.geolocation == 'object'){
    navigator.geolocation.getCurrentPosition(mostrar_ubicacion);
  }
  function mostrar_ubicacion(p) {
    document.getElementById("divtest2").innerHTML = ('<p><label hidden="hidden" for="id_lat">latitud:</label> <input hidden="hidden" id="id_lat" name="lat" step="any" type="number" value="' + p.coords.latitude + '" /></p><p><label hidden="hidden" for="id_lon">longitud:</label> <input hidden="hidden" id="id_lon" name="lon" step="any" type="number" value="' + p.coords.longitude + '" /></p>');
  }
</script>
</body>
</html>